# Generated by Django 2.2.5 on 2019-11-27 19:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('estatus', models.CharField(choices=[(1, 'Pendiente'), (2, 'Aceptado'), (3, 'Rechazado')], max_length=1)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documentos.Documento')),
                ('envia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envia', to=settings.AUTH_USER_MODEL)),
                ('recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
