# Generated by Django 2.2.7 on 2019-12-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesos_b',
            old_name='destinatario_id',
            new_name='destinatario',
        ),
        migrations.RenameField(
            model_name='accesos_b',
            old_name='solicitud_id',
            new_name='solicitud',
        ),
        migrations.RenameField(
            model_name='solicitudes_b',
            old_name='dueno_id',
            new_name='dueno',
        ),
        migrations.RenameField(
            model_name='solicitudes_b',
            old_name='invitado_id',
            new_name='invitado',
        ),
    ]
