# Generated by Django 2.2.5 on 2019-12-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0002_auto_20191201_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpeta',
            old_name='username',
            new_name='usuario',
        ),
    ]
