# Generated by Django 2.2.7 on 2019-12-13 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Documentos', '0003_auto_20191202_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes_b',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=200)),
                ('dueno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dueno', to=settings.AUTH_USER_MODEL)),
                ('invitado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accesos_b',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=200)),
                ('destinatario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to=settings.AUTH_USER_MODEL)),
                ('solicitud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
